import type { AppData } from "./types";

export const seedData: AppData = {
  sessions: [
    {
      id: "s1",
      trainedAt: "2026-03-01T11:00:00+09:00",
      sessionType: "mitt",
      coachName: "Coach A",
      rawNote: "前のめりになる。ジャブのあと重心が前に流れる。ガードの戻りも遅い。",
      selfResult: "same",
    },
    {
      id: "s2",
      trainedAt: "2026-03-03T11:00:00+09:00",
      sessionType: "shadow",
      coachName: "Coach A",
      rawNote: "前のめりは少し良い。ただ右を打つ時に肩が開く。",
      selfResult: "better",
    },
  ],
  corrections: [
    {
      id: "c1",
      title: "前のめりになる",
      normalizedKey: "leaning-forward",
      category: "balance",
      currentState: "today",
      firstSeenAt: "2026-03-01T11:00:00+09:00",
      lastSeenAt: "2026-03-03T11:00:00+09:00",
      resolutionConfidence: 54,
      stalledRisk: 24,
    },
    {
      id: "c2",
      title: "打った後にガードが戻らない",
      normalizedKey: "guard-return",
      category: "guard",
      currentState: "watch",
      firstSeenAt: "2026-03-01T11:00:00+09:00",
      lastSeenAt: "2026-03-01T11:00:00+09:00",
      resolutionConfidence: 31,
      stalledRisk: 48,
    },
    {
      id: "c3",
      title: "右を打つ時に肩が開く",
      normalizedKey: "right-shoulder-open",
      category: "posture",
      currentState: "watch",
      firstSeenAt: "2026-03-03T11:00:00+09:00",
      lastSeenAt: "2026-03-03T11:00:00+09:00",
      resolutionConfidence: 18,
      stalledRisk: 18,
    },
  ],
  observations: [
    {
      id: "o1",
      sessionId: "s1",
      correctionId: "c1",
      rawText: "前のめりになる",
      direction: "same",
      severity: 4,
    },
    {
      id: "o2",
      sessionId: "s1",
      correctionId: "c2",
      rawText: "ガードの戻りが遅い",
      direction: "same",
      severity: 3,
    },
    {
      id: "o3",
      sessionId: "s2",
      correctionId: "c1",
      rawText: "前のめりは少し良い",
      direction: "better",
      severity: 2,
    },
    {
      id: "o4",
      sessionId: "s2",
      correctionId: "c3",
      rawText: "右を打つ時に肩が開く",
      direction: "same",
      severity: 3,
    },
  ],
  focusCycles: [
    {
      id: "f1",
      correctionId: "c1",
      startedAt: "2026-03-01T11:30:00+09:00",
      endedAt: null,
      goalLabel: "頭ではなく足で入る",
      causeHypothesis: "踏み込み時に上半身が先行している",
      cue: "頭ではなく足で入る",
      drill: "ジャブ後に1拍静止して重心を確認するシャドー1R",
      selfCheck: "打った後に重心は腰の真下に戻ったか",
      coachPrompt: "今日は前に流れたらすぐ教えてください",
      evaluationRule: "次の3セッションで指摘頻度が下がるかを見る",
      cycleState: "active",
    },
    {
      id: "f2",
      correctionId: "c2",
      startedAt: "2026-03-01T11:30:00+09:00",
      endedAt: null,
      goalLabel: "打った後すぐ頬に戻す",
      causeHypothesis: "パンチ後に脱力しすぎている",
      cue: "打ったら頬",
      drill: "ワンツー後に必ずガードを触る確認ドリル2分",
      selfCheck: "打ち終わりで右手は頬の近くに戻ったか",
      coachPrompt: "戻りの遅さがあれば教えてください",
      evaluationRule: "次の2セッションで言及がなければ watch に下げる",
      cycleState: "active",
    },
  ],
  interventionChanges: [],
};
